plugins {
    alias(libs.plugins.android.application)


}

android {
    namespace 'com.example.imagecloud'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.example.imagecloud"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'com.squareup.picasso:picasso:2.8'
    // Upgrading to a verified release resolves the missing .aar error
    implementation 'com.cloudinary:cloudinary-android:3.1.2'
    implementation 'com.cloudinary:cloudinary-android-ui:3.1.2'
    implementation 'com.cloudinary:cloudinary-android-preprocess:3.1.2'
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.play.services.cast.tv
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}