plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.imagecloud'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.imagecloud"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // Picasso for Image Loading
    implementation 'com.squareup.picasso:picasso:2.8'
    
    // Cloudinary Android SDK
    implementation 'com.cloudinary:cloudinary-android:3.0.0'
    
    // Core Android Jetpack & Material Design UI
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    
    // Testing Dependencies
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}
